# Generated by Django 5.2.7 on 2026-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetype',
            name='user_role',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='destination',
            field=models.CharField(choices=[('India', 'India'), ('Australia', 'Australia'), ('Bali', 'Bali'), ('Disneyland', 'Disneyland'), ('Dubai', 'Dubai'), ('Greece', 'Greece'), ('Maldives', 'Maldives'), ('Paris', 'Paris'), ('Phuket', 'Phuket')], default='India', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='plan_management',
            field=models.CharField(default='Domestic', max_length=100),
            preserve_default=False,
        ),
    ]
